import { Thermometer, Wind, Wrench, Settings, Shield, AirVent, GitBranch, Sliders, Zap } from "lucide-react"

export const services = [
  {
    slug: "ac-repair",
    title: "AC Repair",
    shortTitle: "AC Repair",
    icon: "Thermometer",
    description: "Fast, reliable air conditioner repairs by certified technicians. We diagnose and fix all AC makes and models.",
    longDescription: "When Denver's heat hits, a broken AC isn't just uncomfortable — it's a health concern. Our certified technicians arrive fully stocked to diagnose and repair any air conditioning issue on the first visit. We service all brands and models, providing upfront pricing before we start any work.",
    href: "/services/ac-repair",
    badge: "Same-Day Available",
    included: [
      "Comprehensive system diagnostic",
      "Refrigerant leak detection and repair",
      "Compressor, capacitor & contactor replacement",
      "Evaporator and condenser coil service",
      "Electrical component inspection and repair",
      "Thermostat calibration",
      "Full system test after repair",
      "90-day parts and labor warranty",
    ],
    process: [
      { step: "1", title: "Schedule", description: "Call or book online. We offer same-day appointments for AC emergencies." },
      { step: "2", title: "Diagnose", description: "Our technician performs a thorough diagnostic and provides upfront pricing." },
      { step: "3", title: "Repair", description: "We fix the issue completely with quality parts backed by warranty." },
      { step: "4", title: "Verify", description: "Full system test to ensure your AC runs at peak performance." },
    ],
    faqs: [
      { q: "How quickly can you repair my AC?", a: "We offer same-day AC repair service for most issues. Emergency repairs are available 24/7." },
      { q: "Do you provide upfront pricing?", a: "Yes, always. We diagnose the issue first, then give you a clear written quote before any work begins." },
      { q: "What brands do you service?", a: "We service all major brands including Carrier, Trane, Lennox, Rheem, York, Goodman, and more." },
      { q: "How long does a typical AC repair take?", a: "Most repairs are completed in 1-3 hours. Complex issues may require a follow-up visit if parts need to be ordered." },
      { q: "Is there a warranty on repairs?", a: "Yes. All repairs come with a 90-day parts and labor warranty." },
    ],
    metaTitle: "AC Repair Denver | Same-Day Service | Summit Climate Solutions",
    metaDescription: "Fast, reliable AC repair in Denver, CO. Certified technicians, upfront pricing, same-day service available. Call Summit Climate Solutions at (555) 820-4400.",
  },
  {
    slug: "ac-installation",
    title: "AC Installation",
    shortTitle: "AC Installation",
    icon: "Wind",
    description: "Professional air conditioner installation with expert sizing, premium brands, and full system commissioning.",
    longDescription: "A properly sized and installed air conditioner is the foundation of home comfort. Our installation specialists perform thorough load calculations, recommend the right system for your home, and complete every installation to manufacturer specifications — ensuring maximum efficiency and longevity.",
    href: "/services/ac-installation",
    badge: "Free Estimates",
    included: [
      "Free in-home assessment and system sizing",
      "Manual J load calculation",
      "Premium brand equipment selection",
      "Professional installation by factory-trained technicians",
      "Refrigerant charging to manufacturer specifications",
      "Full electrical connections and permits",
      "Thermostat installation and programming",
      "10-year manufacturer warranty registration",
    ],
    process: [
      { step: "1", title: "Assess", description: "Free in-home consultation to evaluate your space and cooling needs." },
      { step: "2", title: "Design", description: "We calculate proper sizing and recommend the best system for your home and budget." },
      { step: "3", title: "Install", description: "Factory-trained technicians complete the installation to spec, including all permits." },
      { step: "4", title: "Commission", description: "We verify performance, register your warranty, and walk you through operation." },
    ],
    faqs: [
      { q: "How do I know what size AC I need?", a: "We perform a Manual J load calculation — the industry standard — to determine the exact cooling capacity your home needs. Oversized or undersized systems waste energy and wear out faster." },
      { q: "How long does installation take?", a: "Most residential AC installations are completed in one day, typically 4-8 hours." },
      { q: "What brands do you install?", a: "We install Carrier, Trane, Lennox, Rheem, and other premium brands. We'll help you choose the best fit for your home and budget." },
      { q: "Do you pull permits?", a: "Yes, always. We handle all required permits and inspections for your protection." },
      { q: "What warranty comes with a new AC?", a: "Most new systems include a 10-year manufacturer parts warranty. We also provide a 1-year labor warranty on all installations." },
    ],
    metaTitle: "AC Installation Denver | Expert Sizing & Install | Summit Climate Solutions",
    metaDescription: "Professional AC installation in Denver, CO. Proper sizing, premium brands, full permits. Free estimates. Call Summit Climate Solutions at (555) 820-4400.",
  },
  {
    slug: "heating-repair",
    title: "Heating Repair",
    shortTitle: "Heating Repair",
    icon: "Wrench",
    description: "Keep your home warm through Denver winters. Expert heating system repair for furnaces, heat pumps, and boilers.",
    longDescription: "When your heating fails during a Colorado winter, it's more than an inconvenience. Summit Climate Solutions provides rapid response heating repair with technicians who understand the urgency. We carry an extensive parts inventory so most repairs are completed on the first visit.",
    href: "/services/heating-repair",
    badge: "24/7 Emergency",
    included: [
      "Full heating system diagnostic",
      "Heat exchanger inspection",
      "Ignition system repair and replacement",
      "Blower motor and belt service",
      "Gas valve and pressure testing",
      "Electrical components inspection",
      "Carbon monoxide safety check",
      "90-day parts and labor warranty",
    ],
    process: [
      { step: "1", title: "Call", description: "Call us 24/7. For heating emergencies, we prioritize your call." },
      { step: "2", title: "Diagnose", description: "Thorough diagnostic with upfront pricing before any work begins." },
      { step: "3", title: "Repair", description: "Expert repair with quality parts. Most jobs done in a single visit." },
      { step: "4", title: "Safety Check", description: "Complete safety inspection including CO check before we leave." },
    ],
    faqs: [
      { q: "What heating systems do you repair?", a: "We repair furnaces (gas, electric, oil), heat pumps, boilers, and mini-split systems from all major manufacturers." },
      { q: "Is heating repair available after hours?", a: "Yes. We offer 24/7 emergency heating repair, 365 days a year — including holidays." },
      { q: "How do I know if my furnace needs repair vs. replacement?", a: "Age, repair history, and efficiency are key factors. Our technicians will give you an honest assessment with both options clearly priced so you can make an informed decision." },
      { q: "What are common signs of a failing heater?", a: "Strange noises, short cycling, uneven heating, rising energy bills, yellow pilot flame, or a system that won't turn on are all signs you need service." },
    ],
    metaTitle: "Heating Repair Denver | 24/7 Emergency Service | Summit Climate Solutions",
    metaDescription: "Expert heating repair in Denver, CO. Furnaces, heat pumps, boilers. 24/7 emergency service. Call Summit Climate Solutions at (555) 820-4400.",
  },
  {
    slug: "furnace-installation",
    title: "Furnace Installation",
    shortTitle: "Furnace Install",
    icon: "Settings",
    description: "New high-efficiency furnace installation. Proper sizing, expert installation, full commissioning and warranty.",
    longDescription: "A new furnace is a major investment in your home's comfort and efficiency. Summit Climate Solutions ensures your new system is properly sized, installed to code, and set up for maximum performance. We carry top-tier brands and handle everything from permits to final inspection.",
    href: "/services/furnace-installation",
    badge: "Free Estimates",
    included: [
      "Free in-home assessment and load calculation",
      "High-efficiency equipment selection (up to 98% AFUE)",
      "Professional installation with all required permits",
      "Combustion analysis and safety verification",
      "Carbon monoxide testing",
      "Thermostat installation and programming",
      "Ductwork inspection and sealing",
      "10-year manufacturer warranty registration",
    ],
    process: [
      { step: "1", title: "Assess", description: "We evaluate your home, existing ductwork, and heating needs." },
      { step: "2", title: "Recommend", description: "Honest recommendation on the right system — size, efficiency, and brand." },
      { step: "3", title: "Install", description: "Clean, professional installation with full permits and code compliance." },
      { step: "4", title: "Test", description: "Combustion analysis, CO testing, and full system verification before we leave." },
    ],
    faqs: [
      { q: "How long does furnace installation take?", a: "Most furnace replacements are completed in 4-8 hours. Complete system overhauls with ductwork modifications may take 1-2 days." },
      { q: "What AFUE rating should I choose?", a: "We recommend 95-98% AFUE for Denver's climate. The higher efficiency significantly reduces gas bills and often qualifies for utility rebates." },
      { q: "Can I get utility rebates on a new furnace?", a: "Yes. We help you identify available Xcel Energy rebates and federal tax credits for high-efficiency equipment." },
      { q: "How long will my new furnace last?", a: "With proper maintenance, a quality furnace lasts 20+ years. We offer our Summit Comfort Club membership to keep it running perfectly." },
    ],
    metaTitle: "Furnace Installation Denver | High-Efficiency Systems | Summit Climate Solutions",
    metaDescription: "Professional furnace installation in Denver, CO. High-efficiency systems, proper sizing, full permits. Free estimates. Call (555) 820-4400.",
  },
  {
    slug: "hvac-maintenance",
    title: "HVAC Maintenance",
    shortTitle: "Maintenance",
    icon: "Shield",
    description: "Preventative tune-ups to maximize system life, efficiency, and reliability. Spring AC and fall heating checks.",
    longDescription: "The most cost-effective HVAC service is the one that prevents problems before they happen. Our comprehensive maintenance visits cover every component of your system, ensuring peak efficiency, catching potential failures early, and keeping your warranty valid.",
    href: "/services/hvac-maintenance",
    badge: "Save Up to 30%",
    included: [
      "Full system inspection (40+ point checklist)",
      "Coil cleaning (evaporator and condenser)",
      "Filter replacement (standard filters included)",
      "Refrigerant level check and adjustment",
      "Electrical connections inspection and tightening",
      "Blower motor and belt inspection",
      "Thermostat calibration and testing",
      "Safety controls verification",
    ],
    process: [
      { step: "1", title: "Schedule", description: "Book your spring AC or fall heating tune-up at your convenience." },
      { step: "2", title: "Inspect", description: "Technician completes our comprehensive 40+ point inspection checklist." },
      { step: "3", title: "Service", description: "Cleaning, adjustment, lubrication, and any minor repairs on the spot." },
      { step: "4", title: "Report", description: "Full system health report with recommendations for any future service." },
    ],
    faqs: [
      { q: "How often should I get HVAC maintenance?", a: "Twice yearly — spring for your AC before summer heat, and fall for your heating before winter. This keeps both systems ready when you need them most." },
      { q: "What's the difference between a tune-up and a repair?", a: "Maintenance is preventative — we clean, adjust, and inspect to prevent problems. Repairs fix issues that have already occurred. Regular maintenance dramatically reduces repair frequency." },
      { q: "Will maintenance void my manufacturer warranty?", a: "No — in fact, most manufacturers require documented annual maintenance to keep the warranty valid. We provide service records for your files." },
      { q: "How long does a maintenance visit take?", a: "Typically 60-90 minutes for a single system, 2-2.5 hours for complete HVAC systems." },
    ],
    metaTitle: "HVAC Maintenance Denver | Tune-Up Service | Summit Climate Solutions",
    metaDescription: "Professional HVAC maintenance in Denver, CO. Spring AC and fall heating tune-ups. Maximize efficiency and prevent costly breakdowns. Call (555) 820-4400.",
  },
  {
    slug: "indoor-air-quality",
    title: "Indoor Air Quality",
    shortTitle: "Air Quality",
    icon: "AirVent",
    description: "Breathe cleaner, healthier air. Air purifiers, UV systems, humidifiers, and whole-home filtration solutions.",
    longDescription: "Denver's dry climate and mountain air make indoor air quality a unique challenge. Summit Climate Solutions offers comprehensive IAQ solutions — from advanced filtration and UV air purifiers to whole-home humidifiers — creating a healthier environment for your family.",
    href: "/services/indoor-air-quality",
    badge: "Healthier Home",
    included: [
      "Indoor air quality assessment",
      "Whole-home air purifier installation",
      "UV germicidal light systems",
      "HEPA filtration upgrades",
      "Whole-home humidifier installation",
      "Dehumidification solutions",
      "HRV/ERV ventilation systems",
      "Carbon monoxide detector installation",
    ],
    process: [
      { step: "1", title: "Assess", description: "We evaluate your current air quality, humidity levels, and specific concerns." },
      { step: "2", title: "Recommend", description: "Customized IAQ plan with multiple options and clear pricing." },
      { step: "3", title: "Install", description: "Professional installation integrated with your existing HVAC system." },
      { step: "4", title: "Monitor", description: "Guidance on maintaining your IAQ equipment for lasting results." },
    ],
    faqs: [
      { q: "What is the ideal indoor humidity level in Denver?", a: "Denver's dry climate means indoor humidity often drops below comfortable levels. We recommend maintaining 35-50% relative humidity for comfort and health." },
      { q: "Do air purifiers actually work?", a: "Yes. Whole-home HEPA and UV purifiers are significantly more effective than portable units, treating all the air that passes through your HVAC system." },
      { q: "How do UV air purifiers work?", a: "UV-C light destroys the DNA of bacteria, viruses, and mold spores as air passes through your system, rendering them harmless." },
      { q: "Can IAQ improvements help with allergies?", a: "Absolutely. Advanced filtration removes pollen, pet dander, dust mites, and other allergens from your home's air." },
    ],
    metaTitle: "Indoor Air Quality Denver | Air Purifiers & Humidifiers | Summit Climate Solutions",
    metaDescription: "Improve your home's indoor air quality in Denver, CO. Whole-home air purifiers, UV systems, humidifiers. Call Summit Climate Solutions at (555) 820-4400.",
  },
  {
    slug: "ductwork",
    title: "Ductwork",
    shortTitle: "Ductwork",
    icon: "GitBranch",
    description: "Duct inspection, cleaning, sealing, and replacement. Eliminate efficiency losses and improve airflow throughout your home.",
    longDescription: "Leaky, dirty, or poorly designed ductwork can waste up to 30% of your heating and cooling energy. Summit Climate Solutions provides comprehensive duct services — from inspection and sealing to complete system redesign — maximizing comfort and efficiency in every room.",
    href: "/services/ductwork",
    badge: "Save Up to 30% Energy",
    included: [
      "Full duct system inspection and testing",
      "Blower door and duct pressurization testing",
      "Professional duct sealing (Aeroseal available)",
      "Duct cleaning and sanitizing",
      "Duct insulation upgrade",
      "Zone system installation",
      "New ductwork design and installation",
      "Air balance and flow optimization",
    ],
    process: [
      { step: "1", title: "Inspect", description: "Comprehensive duct inspection including pressurization testing to find leaks." },
      { step: "2", title: "Diagnose", description: "We map the issue — leaks, poor insulation, design flaws, or contamination." },
      { step: "3", title: "Seal & Repair", description: "Professional duct sealing, insulation, or replacement as needed." },
      { step: "4", title: "Verify", description: "Post-service testing confirms improved efficiency and airflow." },
    ],
    faqs: [
      { q: "How do I know if my ducts are leaking?", a: "Signs include rooms that are hard to heat or cool, high energy bills, dusty air, and humidity issues. We can perform a pressurization test to measure leakage precisely." },
      { q: "What is Aeroseal duct sealing?", a: "Aeroseal is an innovative process that seals duct leaks from the inside by pumping a mist of sealant particles through the system. It's highly effective for leaks that are hard to reach physically." },
      { q: "How often should ducts be cleaned?", a: "Generally every 3-5 years, or more frequently if you have pets, smokers in the home, recent renovations, or allergy sufferers." },
      { q: "Can ductwork improvements lower my energy bills?", a: "Yes, significantly. Properly sealed and insulated ducts can reduce HVAC energy use by 20-30%." },
    ],
    metaTitle: "Ductwork Services Denver | Duct Sealing & Repair | Summit Climate Solutions",
    metaDescription: "Professional ductwork inspection, sealing, cleaning, and replacement in Denver, CO. Improve efficiency and comfort. Call Summit Climate Solutions at (555) 820-4400.",
  },
  {
    slug: "thermostat-installation",
    title: "Thermostat Installation",
    shortTitle: "Thermostats",
    icon: "Sliders",
    description: "Smart thermostat installation and programming. Nest, Ecobee, Honeywell, and more. Maximize comfort and savings.",
    longDescription: "A smart thermostat is one of the highest-ROI upgrades for your HVAC system. Summit Climate Solutions installs and programs all major smart thermostat brands, ensuring seamless integration with your heating and cooling system and full optimization of scheduling and energy-saving features.",
    href: "/services/thermostat-installation",
    badge: "Save $180/Year",
    included: [
      "Smart thermostat selection guidance",
      "Professional installation and wiring",
      "Full system compatibility check",
      "Wi-Fi setup and app configuration",
      "Schedule programming for your lifestyle",
      "Geofencing and automation setup",
      "Utility rebate application assistance",
      "Follow-up support included",
    ],
    process: [
      { step: "1", title: "Select", description: "We help you choose the right thermostat for your system and lifestyle." },
      { step: "2", title: "Install", description: "Professional installation with full wiring verification and compatibility check." },
      { step: "3", title: "Program", description: "We set up your schedule, Wi-Fi, and app so you're ready from day one." },
      { step: "4", title: "Optimize", description: "Tips and setup for maximum energy savings based on your habits." },
    ],
    faqs: [
      { q: "Which smart thermostat should I get?", a: "It depends on your system type and lifestyle. Ecobee works excellently with multi-stage and heat pump systems. Nest is intuitive for most users. We'll recommend the best fit after checking your system." },
      { q: "Will a smart thermostat work with my older HVAC system?", a: "Most systems from the past 20+ years are compatible, but we always check wiring compatibility before installation to be certain." },
      { q: "How much will a smart thermostat save me?", a: "The EPA estimates smart thermostats can save up to $180/year. Actual savings depend on your usage patterns and how well it's programmed — we optimize it for your household." },
      { q: "Do I qualify for rebates on a smart thermostat?", a: "Xcel Energy frequently offers rebates on qualifying smart thermostats. We'll check your eligibility at the time of installation." },
    ],
    metaTitle: "Smart Thermostat Installation Denver | Nest, Ecobee | Summit Climate Solutions",
    metaDescription: "Professional smart thermostat installation in Denver, CO. Nest, Ecobee, Honeywell. Save up to $180/year. Call Summit Climate Solutions at (555) 820-4400.",
  },
  {
    slug: "emergency-hvac",
    title: "Emergency HVAC",
    shortTitle: "Emergency Service",
    icon: "Zap",
    description: "24/7 emergency HVAC service. We answer every call, day or night, weekends and holidays. No extra charge for after-hours.",
    longDescription: "HVAC emergencies don't respect business hours. Summit Climate Solutions operates a true 24/7 emergency response — real technicians answering real calls at any hour. No premium surcharges for after-hours service on standard repairs. When your comfort or safety is at risk, we're there.",
    href: "/services/emergency-hvac",
    badge: "24/7/365",
    included: [
      "Live technician answering your call 24/7",
      "Same night emergency dispatch available",
      "No after-hours surcharge (Summit Comfort Club members)",
      "Fully stocked service vehicles",
      "All makes and models serviced",
      "Emergency heating and cooling repair",
      "Gas line safety assessment",
      "Carbon monoxide emergency response",
    ],
    process: [
      { step: "1", title: "Call Now", description: "Call (555) 820-4400 anytime. A real technician answers, 24/7/365." },
      { step: "2", title: "Dispatch", description: "We dispatch the nearest available technician to your location immediately." },
      { step: "3", title: "Diagnose & Repair", description: "Our fully-stocked vehicles mean most emergencies are resolved in one visit." },
      { step: "4", title: "Follow-Up", description: "We check in within 24 hours to confirm your system is performing correctly." },
    ],
    faqs: [
      { q: "Is there a higher charge for emergency service?", a: "For Summit Comfort Club members, there are no after-hours fees. Standard customers pay our normal diagnostic fee. We always quote clearly before starting any work." },
      { q: "What qualifies as an HVAC emergency?", a: "No heat below 40°F, no AC above 90°F, gas smell, carbon monoxide alarm, refrigerant leak, or any complete system failure that poses health or safety risk." },
      { q: "How quickly can you respond to an emergency?", a: "We target a 2-hour response window for genuine emergencies. In some cases — particularly late night — response may be 3-4 hours." },
      { q: "What if you can't fix it the same night?", a: "For heating emergencies in winter, we can often provide temporary space heaters while we source parts. We never leave you without a plan." },
    ],
    metaTitle: "24/7 Emergency HVAC Denver | Same Night Service | Summit Climate Solutions",
    metaDescription: "24/7 emergency HVAC repair in Denver, CO. Real technicians answering every call. No extra after-hours charge for members. Call (555) 820-4400 now.",
  },
]

export type Service = typeof services[0]
