export const testimonials = [
  {
    id: 1,
    name: "Sarah M.",
    location: "Denver, CO",
    rating: 5,
    date: "March 2024",
    text: "Summit Climate saved us during last February's cold snap. Our furnace went out at 10pm and they had a technician at our door by midnight. Professional, efficient, and the repair was done before 1am. I can't recommend them highly enough.",
    service: "Emergency Heating Repair",
    verified: true,
  },
  {
    id: 2,
    name: "James T.",
    location: "Highlands Ranch, CO",
    rating: 5,
    date: "July 2024",
    text: "We got three quotes for a new AC system. Summit was the only company that actually did a load calculation instead of just guessing a size. Their price was fair, the installation was flawless, and it's running perfectly. Very impressive operation.",
    service: "AC Installation",
    verified: true,
  },
  {
    id: 3,
    name: "Linda K.",
    location: "Aurora, CO",
    rating: 5,
    date: "May 2024",
    text: "Their maintenance plan is worth every penny. The technician was thorough, found a small refrigerant leak before it became a problem, and explained everything clearly. No pressure to buy anything I didn't need. This is how service businesses should operate.",
    service: "HVAC Maintenance",
    verified: true,
  },
  {
    id: 4,
    name: "Robert A.",
    location: "Lakewood, CO",
    rating: 5,
    date: "January 2024",
    text: "Called four companies for heating repair and Summit was the only one who could come same day. The tech diagnosed the issue in under 20 minutes, had the part on the truck, and fixed it for a very reasonable price. Exceptional service.",
    service: "Heating Repair",
    verified: true,
  },
  {
    id: 5,
    name: "Michelle P.",
    location: "Littleton, CO",
    rating: 5,
    date: "September 2024",
    text: "Had Summit install a Nest thermostat and they didn't just hook it up — they programmed the whole schedule, set up geofencing, and showed me how to use the app. My energy bill dropped noticeably the first month. Great experience start to finish.",
    service: "Thermostat Installation",
    verified: true,
  },
  {
    id: 6,
    name: "David C.",
    location: "Parker, CO",
    rating: 5,
    date: "August 2024",
    text: "I was skeptical about the duct sealing service but the before/after numbers were undeniable. My leakage rate went from 28% to under 4%. The house heats and cools more evenly now and my utility bills confirm the difference. Money very well spent.",
    service: "Ductwork",
    verified: true,
  },
  {
    id: 7,
    name: "Karen W.",
    location: "Arvada, CO",
    rating: 5,
    date: "April 2024",
    text: "The indoor air quality assessment revealed our humidity was dangerously low — 18% in winter. Summit installed a whole-home humidifier and the difference is remarkable. No more static, better sleep, and my wood floors stopped cracking.",
    service: "Indoor Air Quality",
    verified: true,
  },
  {
    id: 8,
    name: "Tom H.",
    location: "Westminster, CO",
    rating: 5,
    date: "November 2024",
    text: "New furnace installation — the crew was at my door at 8am and finished by 3pm. They cleaned up completely, registered my warranty, and even helped me fill out the Xcel Energy rebate form. Over $400 back. Couldn't be happier.",
    service: "Furnace Installation",
    verified: true,
  },
  {
    id: 9,
    name: "Angela R.",
    location: "Englewood, CO",
    rating: 5,
    date: "June 2024",
    text: "Have been using Summit for 5 years now. Their technicians are always professional, always on time, and always honest. When they tell me something needs to be fixed, I trust them. That's rare to find. Highly recommend their membership plan.",
    service: "Annual Maintenance",
    verified: true,
  },
]

export type Testimonial = typeof testimonials[0]
